# Generated by Django 5.2.2 on 2025-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='bg_image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='prof_image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
